export const DUMMY_CREDENTIALS: Record<string, { role: string; password: string }> = {
  "admin@sanverse.com": { role: "Admin", password: "password123" },
  "principal@sanverse.com": { role: "Principal", password: "password123" },
  "student@sanverse.com": { role: "Student", password: "password123" },
  "teacher@sanverse.com": { role: "Teacher", password: "password123" },
  "hod@sanverse.com": { role: "HOD", password: "password123" },
  "registrar@sanverse.com": { role: "Registrar", password: "password123" },
  "accountant@sanverse.com": { role: "Accountant", password: "password123" },
  "librarian@sanverse.com": { role: "Librarian", password: "password123" },
  "vc@sanverse.com": { role: "Vice Chancellor", password: "password123" },
  "vp@sanverse.com": { role: "Vice Principal", password: "password123" },
  "chancellor@sanverse.com": { role: "Chancellor", password: "password123" },
  "dean@sanverse.com": { role: "Dean", password: "password123" },
  "nurse@sanverse.com": { role: "Nurse", password: "password123" },
  "receptionist@sanverse.com": { role: "Receptionist", password: "password123" },
  "warden@sanverse.com": { role: "Warden", password: "password123" },
  "manager@sanverse.com": { role: "Manager", password: "password123" },
  "auditor@sanverse.com": { role: "Auditor", password: "password123" },
  "alumni@sanverse.com": { role: "Alumni", password: "password123" },
  "vendor@sanverse.com": { role: "Vendor", password: "password123" },
  "coach@sanverse.com": { role: "Coaches", password: "password123" },
  "parent@sanverse.com": { role: "Parent", password: "password123" },
  "superadmin@sanverse.com": { role: "Super Admin", password: "password123" },
  "guild@sanverse.com": { role: "Guild-president", password: "password123" },
  "counselor@sanverse.com": { role: "Counselor", password: "password123" },
  "transport@sanverse.com": { role: "Transport Manager", password: "password123" },
};
