import React, { useState } from "react";
import {
    IoAddOutline,
    IoBarbellOutline,
    IoCalendarOutline,
    IoCheckmarkCircleOutline,
    IoCloseOutline,
    IoDocumentTextOutline,
    IoDownloadOutline,
    IoEyeOutline,
    IoPrintOutline,
    IoSearchOutline,
    IoStatsChartOutline,
    IoWarningOutline
} from "react-icons/io5";

interface Report {
    id: string;
    title: string;
    type: "Performance" | "Attendance" | "Medical" | "Training";
    date: string;
    generatedBy: string;
    status: "Ready" | "Processing" | "Failed";
    size: string;
}

const CoacheReport: React.FC = () => {
    const [searchTerm, setSearchTerm] = useState("");
    const [filterType, setFilterType] = useState<string>("All");
    const [showGenerateModal, setShowGenerateModal] = useState(false);

    // Mock Data
    const [reports, setReports] = useState<Report[]>([
        {
            id: "RPT-001",
            title: "Varsity Soccer Season Summary",
            type: "Performance",
            date: "2024-06-01",
            generatedBy: "Coach Mike",
            status: "Ready",
            size: "2.5 MB"
        },
        {
            id: "RPT-002",
            title: "Q3 Attendance Logs",
            type: "Attendance",
            date: "2024-05-15",
            generatedBy: "Admin",
            status: "Ready",
            size: "1.2 MB"
        },
        {
            id: "RPT-003",
            title: "Injury & Recovery Analysis",
            type: "Medical",
            date: "2024-04-22",
            generatedBy: "Physio Dept",
            status: "Processing",
            size: "-"
        },
        {
            id: "RPT-004",
            title: "Training Plan Adherence",
            type: "Training",
            date: "2024-04-10",
            generatedBy: "Coach Sarah",
            status: "Ready",
            size: "3.8 MB"
        }
    ]);

    const [newReport, setNewReport] = useState({
        title: "",
        type: "Performance",
        team: "Varsity Soccer",
        range: "Last 30 Days"
    });

    const handleGenerateReport = (e: React.FormEvent) => {
        e.preventDefault();
        const report: Report = {
            id: `RPT-${Math.floor(Math.random() * 1000)}`,
            title: newReport.title || `${newReport.team} - ${newReport.type} Report`,
            type: newReport.type as any,
            date: new Date().toISOString().split('T')[0],
            generatedBy: "Coach Mike", // Mock user
            status: "Processing",
            size: "-"
        };
        setReports([report, ...reports]);
        setShowGenerateModal(false);
        
        // Simulate processing
        setTimeout(() => {
            setReports(prev => prev.map(r => r.id === report.id ? { ...r, status: "Ready", size: "1.5 MB" } : r));
        }, 2000);
    };

    const filteredReports = reports.filter(report => 
        (filterType === "All" || report.type === filterType) &&
        (report.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
         report.id.toLowerCase().includes(searchTerm.toLowerCase()))
    );

    const getTypeIcon = (type: string) => {
        switch(type) {
            case "Performance": return <IoStatsChartOutline className="text-blue-500" />;
            case "Attendance": return <IoCheckmarkCircleOutline className="text-green-500" />;
            case "Medical": return <IoWarningOutline className="text-red-500" />;
            case "Training": return <IoBarbellOutline className="text-orange-500" />;
            default: return <IoDocumentTextOutline className="text-gray-500" />;
        }
    };

    const getStatusColor = (status: string) => {
        switch(status) {
            case "Ready": return "bg-green-100 text-green-700";
            case "Processing": return "bg-yellow-100 text-yellow-700";
            case "Failed": return "bg-red-100 text-red-700";
            default: return "bg-gray-100 text-gray-700";
        }
    };


    const [viewReport, setViewReport] = useState<Report | null>(null);

    const handleDownload = (report: Report) => {
        // CSV Content
        const headers = ["Report Title", "Type", "Date Generated", "Generated By", "Status", "Size"];
        const row = [
            `"${report.title}"`,
            report.type,
            report.date,
            report.generatedBy,
            report.status,
            report.size
        ];
        
        const csvContent = [
            headers.join(","),
            row.join(",")
        ].join("\n");

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${report.title.replace(/\s+/g, '_')}.csv`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handlePrint = (report: Report) => {
        const printWindow = window.open('', '_blank');
        if (printWindow) {
            printWindow.document.write(`
                <html>
                    <head>
                        <title>${report.title}</title>
                        <style>
                            body { font-family: sans-serif; padding: 20px; }
                            h1 { color: #333; }
                            .meta { margin-bottom: 20px; color: #666; }
                            .content { border-top: 1px solid #ddd; padding-top: 20px; }
                        </style>
                    </head>
                    <body>
                        <h1>${report.title}</h1>
                        <div class="meta">
                            <p><strong>Date:</strong> ${report.date}</p>
                            <p><strong>Type:</strong> ${report.type}</p>
                            <p><strong>Generated By:</strong> ${report.generatedBy}</p>
                            <p><strong>Status:</strong> ${report.status}</p>
                        </div>
                        <div class="content">
                            <p>This is a simulated report content for demonstration purposes.</p>
                        </div>
                    </body>
                </html>
            `);
            printWindow.document.close();
            printWindow.print();
        }
    };

    return (
        <div className="min-h-screen bg-gray-50/50 p-4 sm:p-6 lg:p-8">
            {/* ... (previous JSX content) ... */}
            <div className={`max-w-7xl mx-auto transition-all duration-300 ${showGenerateModal || viewReport ? "filter blur-sm pointer-events-none" : ""}`}>
                
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8">
                    <div>
                        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 flex items-center gap-3">
                            <IoDocumentTextOutline className="text-primary-100" /> Reports & Analytics
                        </h1>
                        <p className="text-gray-500 mt-1">Generate and export detailed performance insights.</p>
                    </div>
                    <button 
                        onClick={() => setShowGenerateModal(true)}
                        className="flex items-center gap-2 px-6 py-3 bg-primary-100 text-white rounded-xl hover:bg-primary-100/90 font-bold transition-colors shadow-lg shadow-primary-100/30 whitespace-nowrap"
                    >
                        <IoAddOutline className="w-5 h-5" /> Generate Report
                    </button>
                </div>

                {/* Quick Stats */}
                <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
                    <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
                        <div>
                            <p className="text-gray-500 text-xs font-bold uppercase">Total Reports</p>
                            <h3 className="text-2xl font-bold text-gray-900">{reports.length}</h3>
                        </div>
                        <div className="p-3 bg-blue-50 text-blue-500 rounded-xl"><IoDocumentTextOutline className="w-6 h-6" /></div>
                    </div>
                    <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
                        <div>
                            <p className="text-gray-500 text-xs font-bold uppercase">This Month</p>
                            <h3 className="text-2xl font-bold text-gray-900">4</h3>
                        </div>
                        <div className="p-3 bg-green-50 text-green-500 rounded-xl"><IoCalendarOutline className="w-6 h-6" /></div>
                    </div>
                    <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
                        <div>
                            <p className="text-gray-500 text-xs font-bold uppercase">Top Type</p>
                            <h3 className="text-lg font-bold text-gray-900">Performance</h3>
                        </div>
                        <div className="p-3 bg-orange-50 text-orange-500 rounded-xl"><IoStatsChartOutline className="w-6 h-6" /></div>
                    </div>
                     <div className="bg-white p-5 rounded-2xl border border-gray-100 shadow-sm flex items-center justify-between">
                        <div>
                            <p className="text-gray-500 text-xs font-bold uppercase">Storage Used</p>
                            <h3 className="text-2xl font-bold text-gray-900">128 MB</h3>
                        </div>
                        <div className="p-3 bg-purple-50 text-purple-500 rounded-xl"><IoDownloadOutline className="w-6 h-6" /></div>
                    </div>
                </div>

                {/* Filters */}
                <div className="bg-white p-4 rounded-2xl border border-gray-100 shadow-sm mb-6 flex flex-col sm:flex-row gap-4 justify-between items-center">
                    <div className="flex items-center gap-2 overflow-x-auto no-scrollbar w-full sm:w-auto pb-2 sm:pb-0">
                        {(["All", "Performance", "Attendance", "Medical", "Training"] as const).map((type) => (
                            <button
                                key={type}
                                onClick={() => setFilterType(type)}
                                className={`px-4 py-2 rounded-xl text-sm font-bold border transition-colors whitespace-nowrap ${
                                    filterType === type 
                                    ? "bg-gray-900 text-white border-gray-900" 
                                    : "bg-white text-gray-600 border-gray-200 hover:bg-gray-50"
                                }`}
                            >
                                {type}
                            </button>
                        ))}
                    </div>
                    <div className="relative w-full sm:w-64">
                        <IoSearchOutline className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5" />
                        <input
                            type="text"
                            placeholder="Search reports..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="w-full pl-10 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-xl focus:outline-none focus:ring-1 focus:ring-primary-100 transition-all text-sm"
                        />
                    </div>
                </div>

                {/* Reports List */}
                <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left">
                            <thead className="bg-gray-50 text-gray-500 text-xs uppercase font-bold">
                                <tr>
                                    <th className="px-6 py-4">Report Name</th>
                                    <th className="px-6 py-4">Type</th>
                                    <th className="px-6 py-4">Date Generated</th>
                                    <th className="px-6 py-4">Generated By</th>
                                    <th className="px-6 py-4">Status</th>
                                    <th className="px-6 py-4 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {filteredReports.map((report) => (
                                    <tr key={report.id} className="group hover:bg-gray-50/50 transition-colors">
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-3">
                                                <div className="w-10 h-10 rounded-lg bg-gray-100 flex items-center justify-center text-lg">
                                                    {getTypeIcon(report.type)}
                                                </div>
                                                <div>
                                                    <p className="font-bold text-gray-900 text-sm">{report.title}</p>
                                                    <p className="text-xs text-gray-500">{report.id} • {report.size}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className="text-sm font-medium text-gray-600">{report.type}</span>
                                        </td>
                                        <td className="px-6 py-4 text-sm text-gray-600">
                                            {report.date}
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="flex items-center gap-2">
                                                <div className="w-6 h-6 rounded-full bg-primary-100/10 flex items-center justify-center text-xs font-bold text-primary-100">
                                                    {report.generatedBy.charAt(0)}
                                                </div>
                                                <span className="text-sm text-gray-600">{report.generatedBy}</span>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={`px-2 py-1 rounded-lg text-xs font-bold ${getStatusColor(report.status)}`}>
                                                {report.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button 
                                                    onClick={() => setViewReport(report)}
                                                    className="p-2 hover:bg-gray-100 rounded-lg text-gray-500 hover:text-primary-100" 
                                                    title="View"
                                                >
                                                    <IoEyeOutline />
                                                </button>
                                                <button 
                                                    onClick={() => handleDownload(report)}
                                                    className="p-2 hover:bg-gray-100 rounded-lg text-gray-500 hover:text-primary-100" 
                                                    title="Download"
                                                >
                                                    <IoDownloadOutline />
                                                </button>
                                                <button 
                                                    onClick={() => handlePrint(report)}
                                                    className="p-2 hover:bg-gray-100 rounded-lg text-gray-500 hover:text-primary-100" 
                                                    title="Print"
                                                >
                                                    <IoPrintOutline />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                    {filteredReports.length === 0 && (
                        <div className="text-center py-12">
                            <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-300">
                                <IoSearchOutline className="w-8 h-8" />
                            </div>
                            <h3 className="text-lg font-bold text-gray-900">No reports found</h3>
                            <p className="text-gray-500">Try adjusting your filters.</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Generate Report Modal */}
            {showGenerateModal && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowGenerateModal(false)}></div>
                    <div className="relative bg-white rounded-3xl w-full max-w-lg shadow-2xl p-6 animate-scaleIn">
                        <div className="flex justify-between items-center mb-6">
                            <h3 className="text-xl font-bold text-gray-900">Generate New Report</h3>
                            <button onClick={() => setShowGenerateModal(false)} className="p-2 hover:bg-gray-100 rounded-full">
                                <IoCloseOutline className="w-6 h-6" />
                            </button>
                        </div>
                        
                        <form onSubmit={handleGenerateReport} className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Report Title (Optional)</label>
                                <input 
                                    type="text" 
                                    value={newReport.title}
                                    onChange={(e) => setNewReport({...newReport, title: e.target.value})}
                                    className="w-full px-4 py-2 border rounded-xl focus:ring-2 focus:ring-primary-100 outline-none" 
                                    placeholder="Auto-generated if empty"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Report Type</label>
                                    <select 
                                        className="w-full px-4 py-2 border rounded-xl focus:ring-2 focus:ring-primary-100 outline-none"
                                        value={newReport.type}
                                        onChange={(e) => setNewReport({...newReport, type: e.target.value})}
                                    >
                                        <option value="Performance">Performance Analysis</option>
                                        <option value="Attendance">Attendance Log</option>
                                        <option value="Medical">Medical / Injury Report</option>
                                        <option value="Training">Training Adherence</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Date Range</label>
                                    <select 
                                        className="w-full px-4 py-2 border rounded-xl focus:ring-2 focus:ring-primary-100 outline-none"
                                        value={newReport.range}
                                        onChange={(e) => setNewReport({...newReport, range: e.target.value})}
                                    >
                                        <option value="Last 7 Days">Last 7 Days</option>
                                        <option value="Last 30 Days">Last 30 Days</option>
                                        <option value="This Season">This Season</option>
                                        <option value="Custom">Custom Range</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Team Details</label>
                                <select 
                                    className="w-full px-4 py-2 border rounded-xl focus:ring-2 focus:ring-primary-100 outline-none"
                                    value={newReport.team}
                                    onChange={(e) => setNewReport({...newReport, team: e.target.value})}
                                >
                                    <option value="Varsity Soccer">Varsity Soccer</option>
                                    <option value="Varsity Basketball">Varsity Basketball</option>
                                    <option value="JV Volleyball">JV Volleyball</option>
                                    <option value="All Teams">All Teams</option>
                                </select>
                            </div>

                            <div className="bg-yellow-50 p-4 rounded-xl flex items-start gap-3">
                                <IoWarningOutline className="text-yellow-600 w-5 h-5 shrink-0 mt-0.5" />
                                <p className="text-xs text-yellow-700">
                                    Large reports (e.g., "All Teams" + "This Season") may take a few minutes to process. You will be notified when ready.
                                </p>
                            </div>

                            <button type="submit" className="w-full py-3 bg-primary-100 text-white rounded-xl font-bold hover:bg-primary-100/90 transition-colors shadow-lg shadow-primary-100/20 mt-4">
                                Start Generation
                            </button>
                        </form>
                    </div>
                </div>
            )}

            {/* View Report Modal */}
            {viewReport && (
                <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
                    <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setViewReport(null)}></div>
                    <div className="relative bg-white rounded-3xl w-full max-w-2xl shadow-2xl p-6 animate-scaleIn">
                        <div className="flex justify-between items-center mb-6">
                            <h3 className="text-xl font-bold text-gray-900">Report Details</h3>
                            <button onClick={() => setViewReport(null)} className="p-2 hover:bg-gray-100 rounded-full">
                                <IoCloseOutline className="w-6 h-6" />
                            </button>
                        </div>
                        
                        <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100 mb-6">
                            <div className="flex items-center gap-4 mb-4">
                                <div className="w-12 h-12 rounded-xl bg-white border border-gray-200 flex items-center justify-center text-2xl shadow-sm">
                                    {getTypeIcon(viewReport.type)}
                                </div>
                                <div>
                                    <h2 className="text-lg font-bold text-gray-900">{viewReport.title}</h2>
                                    <p className="text-sm text-gray-500">{viewReport.id} • Generated on {viewReport.date}</p>
                                </div>
                            </div>
                            <div className="grid grid-cols-2 gap-4 text-sm">
                                <div>
                                    <p className="text-gray-500 mb-1">Report Type</p>
                                    <p className="font-medium text-gray-900">{viewReport.type}</p>
                                </div>
                                <div>
                                    <p className="text-gray-500 mb-1">Generated By</p>
                                    <p className="font-medium text-gray-900">{viewReport.generatedBy}</p>
                                </div>
                                <div>
                                    <p className="text-gray-500 mb-1">File Size</p>
                                    <p className="font-medium text-gray-900">{viewReport.size}</p>
                                </div>
                                <div>
                                    <p className="text-gray-500 mb-1">Status</p>
                                    <span className={`px-2 py-0.5 rounded text-xs font-bold inline-block mt-0.5 ${getStatusColor(viewReport.status)}`}>
                                        {viewReport.status}
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div className="border-t border-gray-100 pt-6 flex justify-end gap-3">
                            <button 
                                onClick={() => handlePrint(viewReport!)}
                                className="px-4 py-2 border border-gray-200 rounded-xl font-bold text-gray-600 hover:bg-gray-50 transition-colors flex items-center gap-2"
                            >
                                <IoPrintOutline /> Print
                            </button>
                            <button 
                                onClick={() => handleDownload(viewReport!)}
                                className="px-4 py-2 bg-primary-100 text-white rounded-xl font-bold hover:bg-primary-100/90 transition-colors shadow-lg shadow-primary-100/20 flex items-center gap-2"
                            >
                                <IoDownloadOutline /> Download
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default CoacheReport;
